### ISSUE TITLE
Use of CpuId::new() on non-SSE x86 targets?

### ISSUE THREAD

**Issue by A0lson** [gz/rust-cpuid#134]
I was attempting to use this crate on an x86 target (intended for bare-metal code w/o  XMM/SSE register usage). 

However, it seems this crate depends on the Rust target  having `sse` support.  However, just because a processor hardware implements SSE instructions, it seems like the CpuId functionality in this crate should still be available even if the code is being compiled without SSE instruction usage.

Or is there something I'm missing?

**Comment by gz** [comment]
Hi,

The reason for this limitations is [this safety comment](https://github.com/gz/rust-cpuid/blob/master/src/lib.rs#L91).

e.g., there are some ancient x86 architectures which do not have support a cpuid instruction and so the program using this library would crash. The `cpuid_count` function [in the library](https://github.com/gz/rust-cpuid/blob/master/src/lib.rs#L90) was made safe by requiring the SSE feature. In this case, we know the function is recent enough that cpuid exists and therefore won't crash the program.

But you're right that this doesn't per-se has to do anything with SSE, it's more of a hack that will exclude some architectures because we lack proper "is cpuid available" detection at compile-time.
To be precise: Any chip produced after 1993 [has cpuid](https://en.wikipedia.org/wiki/CPUID), but SSE was introduced in 1999. So (Intel) chips created between '93 and '99 technically have a cpuid instruction but can't use this library.

For bare-metal use: I suggest maybe to just fork and remove the compile-time flag? Alternatively, you can also use CpuId [with a custom reader function, that just uses unsafe cpuid](https://docs.rs/raw-cpuid/10.6.1/raw_cpuid/struct.CpuId.html#method.with_cpuid_fn).

**Comment by gz** [comment]
@A0lson does my reply answer your question? Did you figure out how to pass a custom cpuid reader to the CpuId struct?

**Comment by A0lson** [comment]
Thanks for answering this, your reply makes sense.
