### ISSUE TITLE
tsc_frequency fails with a panic, due to a division by zero

### ISSUE THREAD

**Issue by stlankes** [gz/rust-cpuid#31]
Issue hermitcore/libhermit-rs#30 is an example that the denominator of TscInfo isn't alway correctly determined. On some platforms are the denominator 0. In this case, get_tsc_info should return None.

**Comment by gz** [comment]
So it looks like it fails because of https://github.com/gz/rust-cpuid/blob/b64cef2bbfd577b2d3e1c65b8ca76456730efa65/src/lib.rs#L3769

Returning None on `get_tsc_info` is a bit tricky. We already check if the leaf is supported or not: https://github.com/gz/rust-cpuid/blob/b64cef2bbfd577b2d3e1c65b8ca76456730efa65/src/lib.rs#L433
Unfortunately some architectures say the leaf is supported but either set some or all values in TscInfo to just zeros. I've seen this happen in virtual environments for example. Here is a rough example how I typically determine the tsc frequency: https://github.com/gz/rust-cpuid/blob/master/examples/tsc_frequency.rs

I could change
```
pub fn tsc_frequency(&self) -> u64
```
to
```
pub fn tsc_frequency(&self) -> Option<u64>
```

Which would return None if any of those values would be zero that would avoid the division by zero.
Would this solve your problem?

**Comment by stlankes** [comment]
Yes, such a solution would help me and I would find it useful.
